### ISSUE TITLE
command ui localizations

### ISSUE THREAD

**Issue by SuperchupuDev** [Xiboon/Alcan#142]
needs these prs first
- discordjs/discord.js#7683
- #119

**Comment by Nyameliaaaa** [comment]
oh fuck another issue for a discord feature.
also please wait for postgres pr lo

**Comment by hkubus** [comment]
i hate                                    
DISCORD

**Comment by SuperchupuDev** [comment]
this literally doesnt use the database

**Comment by Nyameliaaaa** [comment]
> this literally doesnt use the database

yeah but postgres pr is gonna be immediately made after client cleanup

**Comment by SuperchupuDev** [comment]
postgres and command localizations are totally unrelated and non-blocking from each other, both can exist at the same time
