### ISSUE TITLE
kurwov based ai

### ISSUE THREAD

**Issue by Nyameliaaaa** [Xiboon/Alcan#251]
None of us understand Python:tm: so we should use Kurwov.

**Comment by hkubus** [comment]
good lick

**Comment by hkubus** [comment]
You Fool

**Comment by hkubus** [comment]
> None of us understand Python™️ so we should use Kurwov.

didnt you write like at least 3 bots in pytohn

**Comment by Nyameliaaaa** [comment]
> > None of us understand Python™️ so we should use Kurwov.
> 
> didnt you write like at least 3 bots in pytohn

yes and now i hate it

**Comment by Nyameliaaaa** [comment]
ok so this feature is cancelled because phosphor
