### ISSUE TITLE
ai-powered automod

### ISSUE THREAD

**Issue by Nyameliaaaa** [Xiboon/Alcan#91]
https://www.perspectiveapi.com/

**Comment by Nyameliaaaa** [comment]
~~we could also use https://github.com/ScarletAI/Scarlet~~ nvm

**Comment by hkubus** [comment]
WHY NVM

**Comment by Nyameliaaaa** [comment]
> WHY NVM

owner be like

dumb

**Comment by hkubus** [comment]
OK

**Comment by hkubus** [comment]
i am probably not gonna do this for a while so
